# permissions for end users to edit kubetunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetunnel-editor-role
rules:
- apiGroups:
  - charts.dcode.tech
  resources:
  - kubetunnels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.dcode.tech
  resources:
  - kubetunnels/status
  verbs:
  - get
