apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubetunnel.fullname" . }}
  labels:
    {{- include "kubetunnel.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.pod_selector_labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubetunnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubetunnel.labels" . | nindent 8 }}
        meta.helm.sh/release-name:  {{ .Release.Name }}
        {{- range $key, $val := .Values.pod_selector_labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubetunnel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: kube-exec
          image: bitnami/kubectl
          command:
          - bash
          - -c
          args: 
          - sleep infinity
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - /scripts/health.sh
            initialDelaySeconds: 0
            periodSeconds: 5
          envFrom:
          - configMapRef:
              name: {{ include "kubetunnel.fullname" . }}-env
          volumeMounts:
            - mountPath: /scripts
              name: frp-health
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/frp
              name: frp-conf
          ports:
            {{- range $k,$v := .Values.ports}}
            - name: {{$k}}
              containerPort: {{$v.port}}
              protocol: {{$v.protocol | default "TCP"}}
            {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: frp-conf
          secret:
            {{- if .Values.configSecretName}}
            secretName: {{.Values.configSecretName }}
            {{- else}}
            secretName: {{ include "kubetunnel.fullname" . }}-config
            {{- end}}
        - name: frp-health
          secret:
            {{- if .Values.configSecretName}}
            secretName: {{.Values.configSecretName }}
            {{- else}}
            secretName: {{ include "kubetunnel.fullname" . }}-health
            {{- end}}
            defaultMode: 0777
