{{- $release_name := .Release.Name }}

{{- $job := .Values.job }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $release_name }}-sa
  labels:
    app: {{ $release_name }}
    cron: {{ $job.name }}
