apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kubetunnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $k,$v := .Values.ports}}
    - name: {{$k}}
      targetPort: {{$k}}
      port: {{$v.servicePort | default $v.port}}
      protocol: {{$v.protocol | default "TCP"}}
    {{- end}}
    {{- range $k, $v := .Values.proxy}}
    - protocol: TCP
      port: {{ $v }}
      targetPort: {{ $v }}
    {{- end}}
  selector:
    kubetunnel-app: {{  .Values.env_service_name }}
