# permissions for end users to view kubetunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetunnel-viewer-role
rules:
- apiGroups:
  - application.dcode.tech
  resources:
  - kubetunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.dcode.tech
  resources:
  - kubetunnels/status
  verbs:
  - get
