on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_command: make linux-cli
        goos: linux
        goarch: amd64
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        build_command: make darwin-cli
        goos: darwin
        goarch: amd64
