on:
  push:
    tags:
      - 'kubetunnel-cli-*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1.11.1
        with:
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
